CREATE TABLE IF NOT EXISTS express_parcel (
    pk_parcel           CHAR(20)        NOT NULL,
    pk_group            CHAR(20),
    pk_org              CHAR(20),
    express_no          VARCHAR(100)    NOT NULL,
    receiver_name       VARCHAR(50)     NOT NULL,
    receiver_phone      VARCHAR(20)     NOT NULL,
    pickup_code         VARCHAR(20),
    pickup_code_expire  DATETIME,
    inbound_time        DATETIME        NOT NULL,
    parcel_status       INT             DEFAULT 0,
    is_vip              INT             DEFAULT 0,
    is_large            INT             DEFAULT 0,
    is_remote           INT             DEFAULT 0,
    weight              DECIMAL(28,8),
    area_code           VARCHAR(50),
    return_processing   INT             DEFAULT 0,
    remark              VARCHAR(500),
    creator             CHAR(20),
    creationtime        DATETIME,
    modifier            CHAR(20),
    modifiedtime        DATETIME,
    dr                  INT             DEFAULT 0,
    ts                  CHAR(19),
    PRIMARY KEY (pk_parcel),
    UNIQUE KEY idx_express_no (pk_org, express_no, dr),
    KEY idx_org_status (pk_org, parcel_status),
    KEY idx_return_processing (return_processing),
    KEY idx_pickup_expire (pickup_code_expire)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='快递包裹主表';
