CREATE TABLE IF NOT EXISTS express_reminder_log (
    pk_log              CHAR(20)        NOT NULL,
    pk_group            CHAR(20),
    pk_org              CHAR(20),
    pk_parcel           CHAR(20)        NOT NULL,
    pk_rule             CHAR(20),
    reminder_type       INT             NOT NULL,
    reminder_time       DATETIME        NOT NULL,
    reminder_status     INT             DEFAULT 0,
    reminder_content    VARCHAR(500),
    pickup_code         VARCHAR(20),
    fail_reason         VARCHAR(200),
    reminder_count      INT             DEFAULT 1,
    operator            CHAR(20),
    area_code           VARCHAR(50),
    remark              VARCHAR(500),
    creator             CHAR(20),
    creationtime        DATETIME,
    modifier            CHAR(20),
    modifiedtime        DATETIME,
    dr                  INT             DEFAULT 0,
    ts                  CHAR(19),
    PRIMARY KEY (pk_log),
    KEY idx_parcel (pk_parcel, reminder_time DESC),
    KEY idx_area (pk_org, area_code, reminder_time DESC),
    KEY idx_status (pk_org, reminder_status),
    KEY idx_type_count (pk_org, reminder_type, reminder_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='催领流水表';
