CREATE TABLE IF NOT EXISTS express_reminder_rule (
    pk_rule             CHAR(20)        NOT NULL,
    pk_group            CHAR(20),
    pk_org              CHAR(20),
    rule_code           VARCHAR(50)     NOT NULL,
    rule_name           VARCHAR(100)    NOT NULL,
    cond_vip            INT,
    cond_large          INT,
    cond_remote         INT,
    min_weight          DECIMAL(28,8),
    max_weight          DECIMAL(28,8),
    area_code           VARCHAR(50),
    reminder_type       INT             NOT NULL,
    retention_days      INT             DEFAULT 3,
    reminder_interval   INT             DEFAULT 1,
    max_reminder_count  INT             DEFAULT 5,
    priority            INT             DEFAULT 1,
    enabled             INT             DEFAULT 1,
    remark              VARCHAR(500),
    creator             CHAR(20),
    creationtime        DATETIME,
    modifier            CHAR(20),
    modifiedtime        DATETIME,
    dr                  INT             DEFAULT 0,
    ts                  CHAR(19),
    PRIMARY KEY (pk_rule),
    UNIQUE KEY idx_rule_code (pk_org, rule_code, dr),
    KEY idx_org_priority (pk_org, enabled, dr, priority DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='催领规则表';
